import { Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";
import Navbar from "./_commponent/homepage/NavBar/NavBar";
import "aos/dist/aos.css";
import Footer from "./_commponent/homepage/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const notoKufiArabic = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"], // pick what you need
  variable: "--font-noto-kufi-arabic", // optional but great with Tailwind
});

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body dir="rtl" className={`  antialiased ${notoKufiArabic.className}`}>
        <Navbar />
        <main className="p-">{children}</main>
        <Footer />

      </body>
    </html>
  );
}
