export const userApi = {
  routes: {
    login: "admin/login",
    userProfile: "admin/profile",
    refreshToken: "admin/refresh",
    getBanners: "banner/list",
    createBanners: "banner/create",
    deleteBanner: "banner/delete",
    editBanner: "banner/update",
    getCategories: "category/list",
    createCategory: "category/create",
    updateCategory: "category/update",
    deleteCategory: "category/delete",
    getProducts: "product/list",
    getOffers: "product/offers/list",
    createproduct: "product/create",
    updateproduct: "product/update",
    deleteproduct: "product/delete",
    Installment: "installment/order/delete",
    createOffer: "product/offers/create",
    editOffer: "product/offers/update",
    deleteOffer: "product/offers/delete",
    offerProduct: "product/offers/list",
    deleteOfferProduct: "product/offers/products/delete",
    addOfferProducts: "product/offers/products/create",

    fetchEmployee: "admin/list",
    createEmployee: "admin/create",
    deleteEmployee: "admin/delete",
    updateEmployee: "admin/update",
    fetchUsers: "user/list",
    profile: "user/profile",
    transactions: "admin/transactions/list",
    installmentUpdateStatus: "category/installment/status/update",
    deleteUsers: "user/delete",
    createUser: "user/create",
    updateUser: "user/update",
    fetchContatc: "contacts/list",
    createContact: "contacts/create",
    updateContact: "contacts/update",
    deleteContact: "contacts/delete",
    fetchSocials: "social_media/list",
    createSocial: "social_media/create",
    updateSocials: "social_media/update",
    deleteSocials: "social_media/delete",
    fetchSetting: "settings/list",
    updateSetting: "settings/update",
    fetchNotification: "notification/list",
    fetchInstallments: "installments/list",
    createInstallment: "installments/order/create",
    updateInstallment: "installments/update",
    deleteInstallment: "installments/delete",
    createCategoryInstallment: "category/installment/create",
    deleteCategoryInstallment: "category/installment/delete",
    updateCategoryInstallment: "category/installment/update",
    fetchOrders: "order/list",
    updateOrder: "order/update",
    fetchOrderDetails: "order/details/list",
    fetchOrders: "order/list",
    createOrder: "order/create",
    updateOrder: "order/update",
    fetchOrderDetails: "order/details/list",
    createCart: "user/cart/create",
    fetchCart: "user/cart/list",
    fetchCreditForm: "",
    fetchDeliveryArea: "delivery-areas/list",
    createDeliveryArea: "delivery-areas/create",
    deleteDeliveryArea: "delivery-areas/delete",
    updateDeliveryArea: "delivery-areas/update",
    createGeneralNotification: "notification/createGeneral",
    createOneNotification: "notification/createOne",
    fetchAdminTransaction: "admin/transactions/list",
    fetchStatistics: "admin/statistics",
    updateTransactionInstallment: "category/installment/parts/update",
    sendVerificationCode: "user/send_verify_code",
    verifyCode: "user/verify_code",
    createCreditForm: "credit-forms/create",
    updateCreditForm: "credit-forms/data/update",
    createDeposite: "admin/transactions/deposite/create",
    fetchPermission :"admin/permissions/list",
    createPermission:"admin/permissions/create",
    deletePermission:"admin/permissions/delete",
    updatePermission:"admin/permissions/update",
    createRole:"admin/roles/create",
    fetchRole:"admin/roles/list",
    deleteRole:"admin/roles/delete",
    editRole:"admin/roles/update",
    create_doc:"user/documents/upload",
    update_doc:"user/documents/update",
    delete_doc:"user/documents/delete",
    fetch_doc:"user/documents/list",
    create_user_permission:"admin/roles/permissions/assign",
    get_user_permission:"admin/roles/permissions/list",
    delete_user_permission:"admin/roles/permissions/remove",
    get_admins_transactions :"admin/list-admin-transactions",
    admin_transfer:"admin/transfer",
    resort_category:"category/resort"
  },
};
