export const PERMISSIONS_DATA = [
  {
    id: 1,
    title: "العملاء",
    key: "client",
    value: "clients",
    children: [
      {
        id: 1,
        title: "صفحه العملاء",
        key: "clients_page",
        value: "clients_page",
        children: [
          {
            id: 1,
            title: "اضافه عميل",
            key: "add_client",
            value: "add_client",
          },
          {
            id: 2,
            title: "تعديل عميل",
            key: "edit_client",
            value: "edit_client",
          },
          {
            id: 3,
            title: "حذف العميل",
            key: "delete_client",
            value: "delete_client",
          },
          {
            id: 4,
            title: "ايقاف المستخدم",
            key: "block_user",
            value: "block_user",
          },
        ],
      },
      {
        id: 2,
        title: "عرض صفحه المستخدم",
        key: "view_user_profile",
        value: "view_user_profile",
        children: [
          {
            id: 1,
            title: "تعديل المستخدم",
            key: "edit_user_profile",
            value: "edit_user_profile",
          },
          {
            id: 2,
            title: "تعديل أوراق المستخدم",
            key: "ُedit_docs",
            value: "edit_docs",
          },
          {
            id: 3,
            title: "إرسال الحساب",
            key: "send_balance",
            value: "send_balance",
          },
          {
            id: 4,
            title: "طلبات العميل",
            key: "user_orders",
            value: "user_orders",
          },
          {
            id: 5,
            title: "المعاملات المالية للعملاء",
            key: "user_finance_transactions",
            value: "user_finance_transactions",
          },
        ],
      },
      {
        id: 3,
        title: "طلبات الحساب",
        key: "account_requests",
        value: "account_requests",
        children: [
          {
            id: 1,
            name: "إضافة طلب حساب",
            key: "add_credit_form",
            value: "add_credit_form",
          },
          {
            id: 2,
            name: "تعديل طلب حساب",
            key: "edit_credit_form",
            value: "edit_credit_form",
          },
          {
            id: 3,
            name: "حذف طلب حساب",
            key: "delete_credit_form",
            value: "delete_credit_form",
          },
          {
            id: 4,
            name: "عرض طلب حساب",
            key: "view_credit_form",
            value: "view_credit_form",
          },
          {
            id: 5,
            name: "تغيير حالة طلب حساب",
            key: "change_status_credit_form",
            value: "change_status_credit_form",
          },
        ],
      },
      {
        id: 4,
        title: "المعاملات المالية",
        key: "user_finance_transactions",
        value: "user_finance_transactions",
      },
      {
        id: 5,
        title: "الأقساط",
        key: "clients_installments",
        value: "clients_installments",
      },
      {
        id: 5,
        title: "المعاملات المالية",
        key: "finance_transaction",
        value: "finance_transaction",
        children: [
          {
            id: 1,
            title: "رصيد المحفظة",
            value: "wallet_balance",
            key: "wallet_balance",
            children: [
              {
                id: 1,
                title: "إرسال رصيد",
                key: "send_wallet_balance",
                value: "send_wallet_balance",
              },
              {
                id: 2,
                title: "غرامة",
                key: "wallet_fine",
                value: "wallet_fine",
              },
            ],
          },
          {
            id: 2,
            title: "الأقساط",
            value: "finance_transaction_installments",
            key: "finance_transaction_installments",
            children: [
              {
                id: 1,
                title: "حذف قسط",
                value: "delete_installments",
                key: "delete_installments",
              },
              {
                id: 2,
                title: "تعديل قسط",
                value: "edit_installments",
                key: "edit_installments",
              },
              {
                id: 3,
                title: "عرض قسط",
                value: "view_installments",
                key: "view_installments",
              },
            ],
          },
          {
            id: 3,
            title: "الغرامات",
            key: "fines",
            value: "fines",
          },
          {
            id: 4,
            title: "العمليات",
            key: "finance_transactions_operations",
            value: "finance_transactions_operations",
          },
        ],
      },
    ],
  },
  {
    id: 1,
    title: "الموقع",
    value: "website",
    key: "website",
    children: [
      {
        id: 1,
        title: "الفئات",
        value: "categories",
        key: "categories",
        children: [
          {
            id: 1,
            title: "إضافة فئة",
            key: "add_category",
            value: "add_category",
          },
          {
            id: 2,
            title: "تعديل فئة",
            key: "edit_category",
            value: "edit_category",
          },
          {
            id: 3,
            title: "حذف فئة",
            key: "delete_category",
            value: "delete_category",
          },
          {
            id: 4,
            title: "عرض الأقساط",
            value: "category_installment",
            key: "category_installment",
            children: [
              {
                id: 1,
                title: "تعديل قسط الفئة",
                key: "edit_category_installment",
                value: "edit_category_installment",
              },
              {
                id: 2,
                title: "حذف قسط الفئة",
                key: "delete_category_installment",
                value: "delete_category_installment",
              },
            ],
          },
        ],
      },
      {
        id: 2,
        title: "المنتجات",
        key: "products",
        value: "products",
        children: [
          {
            id: 1,
            title: "إضافة منتج",
            key: "add_product",
            value: "add_product",
          },
          {
            id: 2,
            title: "تعديل منتج",
            key: "edit_product",
            value: "edit_product",
          },
          {
            id: 3,
            title: "حذف منتج",
            key: "delete_product",
            value: "delete_product",
          },
          {
            id: 4,
            title: "صور المنتج",
            key: "product_images",
            value: "product_images",
          },
          {
            id: 5,
            title: "طلبات المنتج",
            key: "product_orders",
            value: "product_orders",
          },
        ],
      },
      {
        id: 3,
        title: "العروض",
        value: "offers",
        key: "offers",
        children: [
          {
            id: 1,
            title: "إضافة عرض",
            value: "add_offer",
            key: "add_offer",
          },
          {
            id: 2,
            title: "تعديل العرض",
            value: "edit_offer",
            key: "edit_offer",
          },
          {
            id: 3,
            title: "حذف العرض",
            value: "delete_offer",
            key: "delete_offer",
          },
          {
            id: 4,
            title: "المنتجات",
            key: "product_offers",
            value: "product_offers",
            children: [
              {
                id: 1,
                title: "إضافة منتج",
                key: "add_product_offer",
                value: "add_product_offer",
              },
              {
                id: 2,
                title: "حذف منتج",
                key: "delete_product_offer",
                value: "delete_product_offer",
              },
            ],
          },
        ],
      },
      {
        id: 4,
        title: "البانرات",
        value: "banners",
        key: "banners",
        children: [
          {
            id: 1,
            title: "إضافة بانر",
            key: "add_banner",
            value: "add_banner",
          },
          {
            id: 2,
            title: "تعديل بانر",
            key: "edit_banner",
            value: "edit_banner",
          },
          {
            id: 3,
            title: "حذف بانر",
            key: "delete_banner",
            value: "delete_banner",
          },
        ],
      },
      {
        id: 5,
        title: "الاعدادات",
        value: "settings",
        key: "settings",
      },
    ],
  },
  {
    id: 3,
    title: "الطلبات",
    value: "all_orders",
    key: "all_orders",
    children: [
      {
        id: 1,
        title: "إنشاء طلب",
        value: "create_order",
        key: "create_order",
      },
      {
        id: 2,
        title: "تعديل الطلب",
        value: "edit_order",
        key: "edit_order",
      },
      {
        id: 3,
        title: "منتجات الاوردر",
        value: "order_products",
        key: "order_products",
      },
      {
        id: 4,
        title: "تفاصيل الاوردر",
        value: "order_details",
        key: "order_details",
      },
      {
        id: 5,
        title: "طباعة",
        key: "print",
        value: "print",
      },
    ],
  },
  {
    id: 4,
    title: "الاشعارات",
    key: "notifications",
    value: "notifications",
  },
  {
    id: 5,
    title: "مناطق التوصيل",
    value: "delivery_areas",
    key: "delivery_areas",
    children: [
      {
        id: 1,
        title: "إضافة منطقة توصيل",
        value: "add_delivery_area",
        key: "add_delivery_area",
      },
      {
        id: 2,
        title: "تعديل منطقة توصيل",
        value: "edit_delivery_area",
        key: "edit_delivery_area",
      },
      {
        id: 3,
        title: "حذف منطقة توصيل",
        value: "delete_delivery_area",
        key: "delete_delivery_area",
      },
    ],
  },
  {
    id: 6,
    title: "الفواتير",
    value: "invoices",
    key: "invoices",
  },
  {
    id: 7,
    ttile: "الموظفين",
    value: "employees",
    key: "employees",
    children: [
      {
        id: 1,
        title: "إضافة موظف",
        key: "add_employee",
        value: "add_employee",
      },
      {
        id: 2,
        title: "تعديل الموظف",
        value: "edit_employee",
        key: "edit_employee",
      },
      {
        id: 3,
        title: "حذف الموظف",
        value: "delete_employee",
        key: "delete_employee",
      },
      {
        id: 4,
        title: "إيقاف الموظف",
        value: "block_employee",
        key: "block_employee",
      },
      {
        id: 5,
        title: "عرض الموظف",
        value: "view_employee",
        key: "view_employee",
      },
      {
        id: 6,
        title: "تعديل أوراق المةظف",
        value: "edit_employee_docs",
        key: "edit_employee_docs",
      },
      {
        id: 7,
        title: "صلاحيات الموظف",
        value: "permissions_employee",
        key: "permissions_employee",
      },
      {
        id: 8,
        title: "إرسال رصيد ",
        value: "send_balance_employee",
        key: "send_balance_employee",
      },
    ],
  },
];
